require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/sms_messages", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # SmsMessage. As you add validations to SmsMessage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SmsMessage.create! valid_attributes
      get sms_messages_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      sms_message = SmsMessage.create! valid_attributes
      get sms_message_url(sms_message)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_sms_message_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      sms_message = SmsMessage.create! valid_attributes
      get edit_sms_message_url(sms_message)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SmsMessage" do
        expect {
          post sms_messages_url, params: { sms_message: valid_attributes }
        }.to change(SmsMessage, :count).by(1)
      end

      it "redirects to the created sms_message" do
        post sms_messages_url, params: { sms_message: valid_attributes }
        expect(response).to redirect_to(sms_message_url(SmsMessage.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SmsMessage" do
        expect {
          post sms_messages_url, params: { sms_message: invalid_attributes }
        }.to change(SmsMessage, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post sms_messages_url, params: { sms_message: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested sms_message" do
        sms_message = SmsMessage.create! valid_attributes
        patch sms_message_url(sms_message), params: { sms_message: new_attributes }
        sms_message.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the sms_message" do
        sms_message = SmsMessage.create! valid_attributes
        patch sms_message_url(sms_message), params: { sms_message: new_attributes }
        sms_message.reload
        expect(response).to redirect_to(sms_message_url(sms_message))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        sms_message = SmsMessage.create! valid_attributes
        patch sms_message_url(sms_message), params: { sms_message: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested sms_message" do
      sms_message = SmsMessage.create! valid_attributes
      expect {
        delete sms_message_url(sms_message)
      }.to change(SmsMessage, :count).by(-1)
    end

    it "redirects to the sms_messages list" do
      sms_message = SmsMessage.create! valid_attributes
      delete sms_message_url(sms_message)
      expect(response).to redirect_to(sms_messages_url)
    end
  end
end
